
-- Datos iniciales para la tabla 'libros' (20 registros)
INSERT INTO libros (titulo, autor, isbn, portada, descripcion, disponible, novedad, destacado, cantidad_busquedas) VALUES
                                                                                                                       ('Cien Años de Soledad', 'Gabriel García Márquez', '978-0307474728', 'https://images.cdn3.buscalibre.com/fit-in/360x360/0d/05/0d05b7ccbff8532459ac819334c4d868.jpg', 'La novela narra la historia de la familia Buendía a lo largo de siete generaciones en el pueblo ficticio de Macondo.', TRUE, TRUE, FALSE, 250),
                                                                                                                       ('1984', 'George Orwell', '978-0451524935', 'https://images.cdn3.buscalibre.com/fit-in/360x360/ea/36/ea367da9370995504dfc6f1348a9871d.jpg', 'Una novela distópica sobre un futuro totalitario donde el Gran Hermano todo lo vigila y el pensamiento independiente es perseguido.', TRUE, FALSE, FALSE, 410),
                                                                                                                       ('Orgullo y Prejuicio', 'Jane Austen', '978-0141439518', 'https://images.cdn3.buscalibre.com/fit-in/360x360/a3/0e/a30e00a4f88090994f05e037183d310f.jpg', 'La historia de las cinco hermanas Bennet y sus peripecias amorosas en la Inglaterra georgiana, centrándose en Elizabeth Bennet y el orgulloso Sr. Darcy.', TRUE, TRUE, TRUE, 295),
                                                                                                                       ('El Señor de los Anillos', 'J.R.R. Tolkien', '978-0618640157', 'https://images.cdn3.buscalibre.com/fit-in/360x360/9d/b0/9db09459397663b6555a3311a68427f7.jpg', 'Una épica de alta fantasía que narra el viaje del hobbit Frodo Bolsón para destruir el Anillo Único y la consiguiente guerra por la Tierra Media.', TRUE, FALSE, TRUE, 550),
                                                                                                                       ('Harry Potter y la piedra filosofal', 'J.K. Rowling', '978-8478884452', 'https://images.cdn3.buscalibre.com/fit-in/360x360/7d/94/7d94f32993142279533261908703444c.jpg', 'La vida de Harry Potter cambia para siempre en su undécimo cumpleaños cuando descubre que es un mago y es invitado a asistir al Colegio Hogwarts de Magia y Hechicería.', TRUE, TRUE, FALSE, 610),
                                                                                                                       ('Dune', 'Frank Herbert', '978-0441013593', 'https://images.cdn3.buscalibre.com/fit-in/360x360/a4/c8/a4c87c71e16f3933c168f865f3f98298.jpg', 'En el distante futuro, en el planeta desértico Arrakis, la única fuente de la especia melange, la sustancia más valiosa del universo, se desarrolla una historia de política, religión y supervivencia.', TRUE, FALSE, FALSE, 380),
                                                                                                                       ('El nombre del viento', 'Patrick Rothfuss', '978-8401337208', 'https://images.cdn3.buscalibre.com/fit-in/360x360/1a/10/1a10423c91af6993540e1e90198bff30.jpg', 'La historia de Kvothe, un músico, aventurero y mago legendario, quien relata su vida a un cronista desde una posada en la que vive de incógnito.', TRUE, TRUE, FALSE, 450),
                                                                                                                       ('Juego de Tronos', 'George R.R. Martin', '978-0553386790', 'https://images.cdn3.buscalibre.com/fit-in/360x360/c1/e0/c1e0413000a35948951ba86236b3f790.jpg', 'En el continente de Poniente, varias casas nobles luchan por el control del Trono de Hierro, mientras una antigua amenaza resurge en el norte.', FALSE, FALSE, FALSE, 520),
                                                                                                                       ('Sapiens: De animales a dioses', 'Yuval Noah Harari', '978-0062316097', 'https://images.cdn3.buscalibre.com/fit-in/360x360/e2/09/e20967397b91d293f0b06b6b553e875a.jpg', 'Una breve historia de la humanidad que explora cómo el Homo sapiens llegó a dominar el mundo y las revoluciones (cognitiva, agrícola, científica) que lo hicieron posible.', TRUE, TRUE, TRUE, 310),
                                                                                                                       ('Hábitos Atómicos', 'James Clear', '978-0735211292', 'https://images.cdn3.buscalibre.com/fit-in/360x360/2c/61/2c61148419c8f07452d3c713601e3b3c.jpg', 'Un marco de trabajo práctico para mejorar cada día. Ofrece estrategias sobre cómo formar buenos hábitos, romper los malos y dominar los pequeños comportamientos que conducen a resultados notables.', TRUE, FALSE, FALSE, 220),
                                                                                                                       ('El Alquimista', 'Paulo Coelho', '978-0061122415', 'https://images.cdn3.buscalibre.com/fit-in/360x360/9d/4e/9d4e511413861217e6922d9b6279f6e6.jpg', 'La historia de Santiago, un joven pastor andaluz que viaja desde su tierra natal en España al desierto egipcio en busca de un tesoro oculto en las Pirámides.', TRUE, TRUE, FALSE, 340),
                                                                                                                       ('Crimen y castigo', 'Fiódor Dostoievski', '978-0140449136', 'https://images.cdn3.buscalibre.com/fit-in/360x360/0d/67/0d67a14c33c2a68c4bc62d089f812543.jpg', 'Sigue el dilema mental y el tormento moral de Rodion Raskólnikov, un ex-estudiante empobrecido en San Petersburgo que formula y ejecuta un plan para matar a una usurera sin escrúpulos.', TRUE, FALSE, FALSE, 180),
                                                                                                                       ('La chica salvaje', 'Delia Owens', '978-0735219090', 'https://images.cdn3.buscalibre.com/fit-in/360x360/e2/57/e2579b9a67a07ac411394f79432e185f.jpg', 'Una oda a la naturaleza, una desgarradora historia sobre la madurez y un sorprendente relato de un posible asesinato. Sigue la vida de Kya, una niña abandonada que crece en las marismas de Carolina del Norte.', FALSE, TRUE, FALSE, 255),
                                                                                                                       ('El poder del ahora', 'Eckhart Tolle', '978-1577314806', 'https://images.cdn3.buscalibre.com/fit-in/360x360/1a/c2/1ac233519b5311090382281a7f722340.jpg', 'Una guía para la iluminación espiritual que enfatiza la importancia de vivir en el momento presente para evitar el dolor y la ansiedad del pensamiento.', TRUE, FALSE, FALSE, 195),
                                                                                                                       ('Fahrenheit 451', 'Ray Bradbury', '978-1451673319', 'https://images.cdn3.buscalibre.com/fit-in/360x360/f2/31/f2312b1d7d23f73663a8635c91f69206.jpg', 'En un futuro distópico, los libros están prohibidos y los "bomberos" tienen la misión de quemar cualquiera que encuentren. La historia sigue a Guy Montag, un bombero que empieza a cuestionar su rol.', TRUE, FALSE, FALSE, 330),
                                                                                                                       ('El sutil arte de que te importe un caraj*', 'Mark Manson', '978-0062457714', 'https://images.cdn3.buscalibre.com/fit-in/360x360/45/a1/45a1f0a1420b93892c90cbe89280058e.jpg', 'Un enfoque contraintuitivo para vivir una buena vida, argumentando que la clave no es la positividad implacable, sino aprender a manejar mejor la adversidad y elegir qué batallas vale la pena luchar.', TRUE, FALSE, FALSE, 240),
                                                                                                                       ('El guardián entre el centeno', 'J.D. Salinger', '978-0316769488', 'https://images.cdn3.buscalibre.com/fit-in/360x360/3d/8d/3d8d21c33f28d844c82c3c52e46da8a1.jpg', 'Narra las experiencias de Holden Caulfield, un joven de dieciséis años que se enfrenta a la hipocresía del mundo adulto tras ser expulsado de su internado.', FALSE, FALSE, FALSE, 210),
                                                                                                                       ('La sombra del viento', 'Carlos Ruiz Zafón', '978-0143126393', 'https://images.cdn3.buscalibre.com/fit-in/360x360/ab/23/ab23e5907409c9102c7b415a9ab35b43.jpg', 'En la Barcelona de 1945, el joven Daniel Sempere es llevado por su padre al Cementerio de los Libros Olvidados, donde encuentra un libro misterioso que cambiará el curso de su vida.', TRUE, TRUE, FALSE, 480),
                                                                                                                       ('Matadero cinco', 'Kurt Vonnegut', '978-0385334232', 'https://images.cdn3.buscalibre.com/fit-in/360x360/88/53/8853ebc8397a6e19199d3fc54673c66f.jpg', 'Una novela antibélica con elementos de ciencia ficción que sigue la vida de Billy Pilgrim, un soldado estadounidense que sobrevive al bombardeo de Dresde y experimenta los eventos de su vida en un orden no lineal.', TRUE, FALSE, FALSE, 170),
                                                                                                                       ('Los hombres me explican cosas', 'Rebecca Solnit', '978-1608463862', 'https://images.cdn3.buscalibre.com/fit-in/360x360/eb/64/eb646f254e0f10a8867a1467bd182d8d.jpg', 'Una colección de ensayos que aborda el silenciamiento de las mujeres en la sociedad, comenzando con el ensayo viral que dio origen al término "mansplaining".', TRUE, TRUE, FALSE, 155);

-- Asegúrate de tener tus sentencias INSERT INTO usuarios aquí si quieres que se carguen también
-- INSERT INTO usuarios (nombre, correo, contrasena, rol) VALUES ...
-- Datos iniciales para la tabla 'usuarios'

INSERT INTO usuarios (nombre, correo, contrasena, rol) VALUES
('Usuario de Prueba', 'usuario@test.com', 'password123', 'USUARIO'),
('Admin Biblioteca', 'admin@biblioteca.com', 'adminpass', 'ADMINISTRADOR');

